In [2]:
import numpy as np

# Your provided dataset
data_array = np.array([
    [1001, 207, 307, 2, 8.5, 0, 4, 'West', 'PayPal', 503.0, 17.00],
    [1002, 206, 305, 4, 10.99, 5, 6, 'Online', 'Cash', np.nan, 41.75],
    [1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', np.nan, 49.46],
    [1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0, 13.05],
    [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
    [1006, 208, 308, 1, 12.75, 0, 0, 'East', 'Cash', 502.0, 12.75],
    [1007, 206, 302, 3, 7.25, 0, 1, 'Online', 'PayPal', np.nan, 21.75],
    [1008, 206, 308, 1, 10.99, 5, 8, 'West', 'Credit Card', 503.0, 10.44],
    [1009, 204, 304, 5, 25.5, 0, 6, 'South', 'Credit Card', 501.0, 127.50],
    [1010, 210, 302, 3, 8.5, 0, 4, 'North', 'Debit Card', 503.0, 25.50],
    [1011, 202, 305, 3, 8.5, 0, 1, 'North', 'PayPal', 501.0, 25.50],
    [1012, 205, 301, 1, 10.99, 0, 1, 'West', 'Debit Card', 503.0, 10.99],
    [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0, 45.90],
    [1014, 202, 304, 1, 12.75, 5, 5, 'East', 'Cash', 501.0, 12.11],
    [1015, 208, 303, 5, 49.99, 5, 4, 'Online', 'Credit Card', np.nan, 237.41],
    [1016, 207, 301, 2, 10.99, 5, 5, 'West', 'Credit Card', 503.0, 20.88],
    [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78],
    [1018, 202, 302, 5, 49.99, 5, 8, 'North', 'Credit Card', 503.0, 237.41],
    [1019, 208, 304, 2, 7.25, 5, 7, 'South', 'Debit Card', 502.0, 13.78],
    [1020, 206, 305, 3, 25.5, 10, 0, 'South', 'Debit Card', 503.0, 68.85]
], dtype=object)



In [3]:
data_array.shape

(20, 11)

In [4]:
data_array.dtype

dtype('O')

In [5]:
quantities = data_array[:, 3].astype(int); np.sum(quantities)

np.int64(54)

In [6]:
total_sales = data_array[:, 10].astype(float); np.mean(total_sales)

np.float64(55.0895)

In [7]:
data_array[0, 7]

'West'

In [8]:
data_array[:, 8].size

20

In [11]:
data_array[0, :]


array([1001, 207, 307, 2, 8.5, 0, 4, 'West', 'PayPal', 503.0, 17.0],
      dtype=object)

In [12]:
data_array[0]

array([1001, 207, 307, 2, 8.5, 0, 4, 'West', 'PayPal', 503.0, 17.0],
      dtype=object)

In [13]:
type(data_array[0, 9])

float

In [14]:
transaction_ids = data_array[:, 0].astype(int); np.all(transaction_ids == data_array[:, 0])

np.True_

In [15]:
numerical_data = data_array[:, [0,1,2,3,4,5,6,10]].astype(float)

In [16]:
np.max(data_array[:, 3].astype(int))

np.int64(5)

In [17]:
np.min(data_array[:, 4].astype(float))

np.float64(7.25)

In [18]:
np.sum(data_array[:, 5].astype(int))

np.int64(95)

In [19]:
np.median(data_array[:, 10].astype(float))

np.float64(23.625)

In [20]:
np.std(data_array[:, 4].astype(float))

np.float64(14.49983124039725)

In [21]:
len(np.unique(data_array[:, 1].astype(int)))

8

In [22]:
len(np.unique(data_array[:, 2].astype(int)))

8

In [23]:
discounts = data_array[:, 5].astype(int); quantities = data_array[:, 3].astype(int); np.sum(quantities[discounts == 0])

np.int64(18)

In [24]:
quantities = data_array[:, 3].astype(int); total_sales = data_array[:, 10].astype(float); np.mean(total_sales[quantities > 3])

np.float64(138.706)

In [25]:
quantities = data_array[:, 3].astype(int); unit_prices = data_array[:, 4].astype(float); np.sum(quantities * unit_prices)

np.float64(1163.98)

In [26]:
store_locations = data_array[:, 7]; total_sales = data_array[:, 10].astype(float); np.sum(total_sales[store_locations == 'Online'])


np.float64(350.37)

In [27]:
payment_types = data_array[:, 8]; np.sum(payment_types == 'PayPal')

np.int64(6)

In [28]:
salespersons = data_array[:, 9]; discounts = data_array[:, 5].astype(int); np.mean(discounts[salespersons == 501.0])

np.float64(3.75)

In [29]:
salespersons = data_array[:, 9]; np.sum(~(salespersons == np.nan))

np.int64(20)

In [30]:
np.min(data_array[:, 6].astype(int))

np.int64(0)

In [31]:
product_ids = data_array[:, 2].astype(int); transaction_ids = data_array[:, 0].astype(int); transaction_ids[product_ids == 301]

array([1003, 1012, 1016])

In [32]:
store_locations = data_array[:, 7]; total_sales = data_array[:, 10].astype(float); total_sales[store_locations == 'West']

array([17.  , 13.05, 89.98, 10.44, 10.99, 20.88])

In [33]:
store_locations = data_array[:, 7]; quantities = data_array[:, 3].astype(int); np.sum((store_locations == 'Online') & (quantities == 5))

np.int64(2)

In [34]:
payment_types = data_array[:, 8]; total_sales = data_array[:, 10].astype(float); customer_ids = data_array[:, 1].astype(int); customer_ids[(payment_types == 'Credit Card') & (total_sales > 50)]

array([204, 208, 202])

In [35]:
discounts = data_array[:, 5].astype(int); data_array[discounts == 10, :]

array([[1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', nan, 49.46],
       [1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
       [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0,
        45.9],
       [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78],
       [1020, 206, 305, 3, 25.5, 10, 0, 'South', 'Debit Card', 503.0,
        68.85]], dtype=object)

In [36]:
product_ids = data_array[:, 2].astype(int); store_locations = data_array[:, 7]; unit_prices = data_array[:, 4].astype(float); unit_prices[(product_ids == 307) & (store_locations == 'West')]

array([8.5 , 7.25])

In [37]:
salespersons = data_array[:, 9]; np.sum(salespersons == np.nan)

np.int64(0)

In [39]:
np.sum(np.array([x is np.nan for x in data_array[:, 9]]))

np.int64(4)

In [40]:
discounts = data_array[:, 5].astype(int); total_sales = data_array[:, 10].astype(float); total_sales[discounts == 0]


array([ 17.  ,  12.75,  21.75, 127.5 ,  25.5 ,  25.5 ,  10.99])

In [41]:
 quantities = data_array[:, 3].astype(int); transaction_ids = data_array[:, 0].astype(int); transaction_ids[(quantities == 1) | (quantities == 5)]


array([1003, 1006, 1008, 1009, 1012, 1014, 1015, 1018])

In [42]:
store_locations = data_array[:, 7]; np.sum(np.isin(store_locations, ['North', 'South']))

np.int64(8)

In [43]:
payment_types = data_array[:, 8]; data_array[payment_types != 'Cash', :]

array([[1001, 207, 307, 2, 8.5, 0, 4, 'West', 'PayPal', 503.0, 17.0],
       [1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', nan, 49.46],
       [1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
       [1007, 206, 302, 3, 7.25, 0, 1, 'Online', 'PayPal', nan, 21.75],
       [1008, 206, 308, 1, 10.99, 5, 8, 'West', 'Credit Card', 503.0,
        10.44],
       [1009, 204, 304, 5, 25.5, 0, 6, 'South', 'Credit Card', 501.0,
        127.5],
       [1010, 210, 302, 3, 8.5, 0, 4, 'North', 'Debit Card', 503.0, 25.5],
       [1011, 202, 305, 3, 8.5, 0, 1, 'North', 'PayPal', 501.0, 25.5],
       [1012, 205, 301, 1, 10.99, 0, 1, 'West', 'Debit Card', 503.0,
        10.99],
       [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0,
        45.9],
       [1015, 208, 303, 5, 49.99, 5, 4, 'Online', 'Credit Card', nan,
        237.41],
       [1016, 207, 301, 2, 10.99, 5, 5, 'West', 

In [44]:
total_sales = data_array[:, 10].astype(float); product_ids = data_array[:, 2].astype(int); product_ids[(total_sales >= 10) & (total_sales <= 20)]

array([307, 307, 308, 308, 301, 304, 303, 304])

In [45]:
salespersons = data_array[:, 9]; discounts = data_array[:, 5].astype(int); np.sum((salespersons == 503.0) & (discounts > 0))

np.int64(4)

In [46]:
transaction_days = data_array[:, 6].astype(int); data_array[transaction_days == 0, :]

array([[1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1006, 208, 308, 1, 12.75, 0, 0, 'East', 'Cash', 502.0, 12.75],
       [1020, 206, 305, 3, 25.5, 10, 0, 'South', 'Debit Card', 503.0,
        68.85]], dtype=object)

In [47]:
store_locations = data_array[:, 7]; east_indices = (store_locations == 'East'); data_array[east_indices][:, [0, 10]]


array([[1006, 12.75],
       [1014, 12.11]], dtype=object)

In [48]:
product_ids = data_array[:, 2].astype(int); quantities = data_array[:, 3].astype(int); np.sum((product_ids == 304) & (quantities == 1))

np.int64(1)

In [49]:
customer_ids = data_array[:, 1].astype(int); payment_types = data_array[:, 8]; total_sales = data_array[:, 10].astype(float); total_sales[(customer_ids == 206) & (payment_types == 'Cash')]


array([41.75])

In [50]:
np.unique(data_array[:, 7])

array(['East', 'North', 'Online', 'South', 'West'], dtype=object)

In [51]:
unit_prices = data_array[:, 4].astype(float); data_array[np.isclose(unit_prices, 10.99), :]

array([[1002, 206, 305, 4, 10.99, 5, 6, 'Online', 'Cash', nan, 41.75],
       [1003, 205, 301, 5, 10.99, 10, 6, 'Online', 'PayPal', nan, 49.46],
       [1008, 206, 308, 1, 10.99, 5, 8, 'West', 'Credit Card', 503.0,
        10.44],
       [1012, 205, 301, 1, 10.99, 0, 1, 'West', 'Debit Card', 503.0,
        10.99],
       [1016, 207, 301, 2, 10.99, 5, 5, 'West', 'Credit Card', 503.0,
        20.88],
       [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78]],
      dtype=object)

In [52]:
salespersons = data_array[:, 9]; data_array[np.isin(salespersons, [501.0, 502.0]), :]

array([[1004, 206, 307, 2, 7.25, 10, 0, 'West', 'Credit Card', 501.0,
        13.05],
       [1005, 207, 306, 2, 49.99, 10, 6, 'West', 'PayPal', 502.0, 89.98],
       [1006, 208, 308, 1, 12.75, 0, 0, 'East', 'Cash', 502.0, 12.75],
       [1009, 204, 304, 5, 25.5, 0, 6, 'South', 'Credit Card', 501.0,
        127.5],
       [1011, 202, 305, 3, 8.5, 0, 1, 'North', 'PayPal', 501.0, 25.5],
       [1013, 206, 307, 2, 25.5, 10, 1, 'North', 'Credit Card', 502.0,
        45.9],
       [1014, 202, 304, 1, 12.75, 5, 5, 'East', 'Cash', 501.0, 12.11],
       [1017, 203, 303, 2, 10.99, 10, 5, 'North', 'PayPal', 502.0, 19.78],
       [1019, 208, 304, 2, 7.25, 5, 7, 'South', 'Debit Card', 502.0,
        13.78]], dtype=object)

In [53]:
data_array[:, 4].astype(float) * data_array[:, 3].astype(int)

array([ 17.  ,  43.96,  54.95,  14.5 ,  99.98,  12.75,  21.75,  10.99,
       127.5 ,  25.5 ,  25.5 ,  10.99,  51.  ,  12.75, 249.95,  21.98,
        21.98, 249.95,  14.5 ,  76.5 ])

In [54]:
(data_array[:, 4].astype(float) * data_array[:, 3].astype(int) * data_array[:, 5].astype(int)) / 100.0


array([ 0.    ,  2.198 ,  5.495 ,  1.45  ,  9.998 ,  0.    ,  0.    ,
        0.5495,  0.    ,  0.    ,  0.    ,  0.    ,  5.1   ,  0.6375,
       12.4975,  1.099 ,  2.198 , 12.4975,  0.725 ,  7.65  ])

In [55]:
data_array[:, 10].astype(float) > 75

array([False, False, False, False,  True, False, False, False,  True,
       False, False, False, False, False,  True, False, False,  True,
       False, False])

In [56]:
data_array[:, 10].astype(float) * 1.05

array([ 17.85  ,  43.8375,  51.933 ,  13.7025,  94.479 ,  13.3875,
        22.8375,  10.962 , 133.875 ,  26.775 ,  26.775 ,  11.5395,
        48.195 ,  12.7155, 249.2805,  21.924 ,  20.769 , 249.2805,
        14.469 ,  72.2925])

In [57]:
np.where(data_array[:, 10].astype(float) > 100, 1, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0])

In [58]:
total_sales = data_array[:, 10].astype(float); quantities = data_array[:, 3].astype(int); np.divide(total_sales, quantities, out=np.zeros_like(total_sales), where=quantities!=0)

array([ 8.5   , 10.4375,  9.892 ,  6.525 , 44.99  , 12.75  ,  7.25  ,
       10.44  , 25.5   ,  8.5   ,  8.5   , 10.99  , 22.95  , 12.11  ,
       47.482 , 10.44  ,  9.89  , 47.482 ,  6.89  , 22.95  ])

In [59]:
(data_array[:, 4].astype(float) * data_array[:, 3].astype(int)) - data_array[:, 10].astype(float)


array([ 0.  ,  2.21,  5.49,  1.45, 10.  ,  0.  ,  0.  ,  0.55,  0.  ,
        0.  ,  0.  ,  0.  ,  5.1 ,  0.64, 12.54,  1.1 ,  2.2 , 12.54,
        0.72,  7.65])