In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[5, 8, 3],
       [2, 8, 0],
       [5, 2, 7]])

In [ ]:
data.sum()

np.int64(40)

In [ ]:
data.sum(axis=1)

array([16, 10, 14])

In [ ]:
data.sum(axis=0)

array([12, 18, 10])

In [ ]:
data.max(axis=0)#### here it gives max value in each from 1, 2, 3 rows

array([5, 8, 7])

In [ ]:
data

array([[5, 8, 3],
       [2, 8, 0],
       [5, 2, 7]])

In [ ]:
data.argmax(axis=1) ### here argmax means it gives max values in each coloumn..

array([1, 1, 2])

In [ ]:
data=np.random.randint(0,100,(10,5))

In [ ]:
data

array([[24, 93, 87, 74, 19],
       [37, 65, 78,  2, 87],
       [92, 64,  9, 87, 21],
       [36,  4,  1, 28, 40],
       [27, 95, 88, 64, 36],
       [41, 62,  8, 39, 40],
       [41, 54,  8, 91, 81],
       [49, 26, 57, 37, 78],
       [65, 67, 35, 48, 45],
       [84, 33, 78,  9, 73]])

In [ ]:
data.sum(axis=1)

array([297, 269, 273, 109, 310, 190, 275, 247, 260, 277])

In [ ]:
data.sum(axis=1).argmin()+1

np.int64(4)

In [ ]:
data.sum(axis=1).argsort()[:2] + 1

array([4, 6])

In [ ]:
data.sum(axis=0)[3]

np.int64(479)

In [ ]:
data.sum(axis=0)[3:].sum()

np.int64(999)

In [ ]:
data

array([[24, 93, 87, 74, 19],
       [37, 65, 78,  2, 87],
       [92, 64,  9, 87, 21],
       [36,  4,  1, 28, 40],
       [27, 95, 88, 64, 36],
       [41, 62,  8, 39, 40],
       [41, 54,  8, 91, 81],
       [49, 26, 57, 37, 78],
       [65, 67, 35, 48, 45],
       [84, 33, 78,  9, 73]])

In [ ]:
data.sum(axis=1).min()

np.int64(109)

In [ ]:
data.sum(axis=1)

array([297, 269, 273, 109, 310, 190, 275, 247, 260, 277])

In [ ]:
data.sum(axis=1).argsort()

array([3, 5, 7, 8, 1, 2, 6, 9, 0, 4])

In [ ]:
data.mean()

np.float64(50.14)

In [ ]:
data

array([[24, 93, 87, 74, 19],
       [37, 65, 78,  2, 87],
       [92, 64,  9, 87, 21],
       [36,  4,  1, 28, 40],
       [27, 95, 88, 64, 36],
       [41, 62,  8, 39, 40],
       [41, 54,  8, 91, 81],
       [49, 26, 57, 37, 78],
       [65, 67, 35, 48, 45],
       [84, 33, 78,  9, 73]])

In [ ]:
data.mean()

np.float64(50.14)

In [ ]:
np.median(data)

np.float64(46.5)

In [ ]:
data

array([[24, 93, 87, 74, 19],
       [37, 65, 78,  2, 87],
       [92, 64,  9, 87, 21],
       [36,  4,  1, 28, 40],
       [27, 95, 88, 64, 36],
       [41, 62,  8, 39, 40],
       [41, 54,  8, 91, 81],
       [49, 26, 57, 37, 78],
       [65, 67, 35, 48, 45],
       [84, 33, 78,  9, 73]])

In [ ]:
np.quantile(data,0.25)

np.float64(29.25)

In [ ]:
np.quantile(data,0.50)

np.float64(46.5)

In [ ]:
np.median(data)

np.float64(46.5)

In [ ]:
### DESCRIPTIVE STATISTICS
mean
median
max
min
range
q1
q3
iqr(interquantile range)
std(standard deviation)
var(variance)

In [ ]:
np.std(data)

np.float64(28.042118322266596)

In [ ]:
np.var(data)

np.float64(786.3603999999999)

In [ ]:
data=np.random.randint(0,10,(10,2))

In [ ]:
np.corrcoef(data.T)

array([[1.        , 0.08887695],
       [0.08887695, 1.        ]])

In [ ]:
v1=np.arange(1,11)

In [ ]:
v2=np.arange(10,20)

In [ ]:
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x=[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
x.reverse()
v2=np.array(x)
v2

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [ ]:
data[:,0]=v1
data[:,1]=v2

In [ ]:
np.corrcoef(data.T)

array([[ 1., -1.],
       [-1.,  1.]])

In [ ]:
data=np.random.randint(0,10,(5,5))

In [ ]:
np.corrcoef(data)

array([[ 1.        ,  0.17609018, -0.63481105,  0.73611111, -0.30588765],
       [ 0.17609018,  1.        ,  0.30740598, -0.17609018, -0.72716145],
       [-0.63481105,  0.30740598,  1.        , -0.21748156, -0.16990825],
       [ 0.73611111, -0.17609018, -0.21748156,  1.        , -0.01274532],
       [-0.30588765, -0.72716145, -0.16990825, -0.01274532,  1.        ]])